wandb_version: 1

learning_rate:
  desc: null
  value: 0.001
epochs:
  desc: null
  value: 10
batch_size:
  desc: null
  value: 64
_wandb:
  desc: null
  value:
    python_version: 3.9.15
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712544654.0
    t:
      1:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.9.15
      5: 0.16.6
      8:
      - 3
      - 5
      13: windows-amd64
