wandb_version: 1

learning_rate:
  desc: null
  value: 0.001
epochs:
  desc: null
  value: 20
batch_size:
  desc: null
  value: 64
validation_split:
  desc: null
  value: 0.2
_wandb:
  desc: null
  value:
    python_version: 3.9.15
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712844451.0
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.9.15
      5: 0.16.6
      8:
      - 3
      - 5
      13: windows-amd64
