wandb_version: 1

zero_shot:
  desc: null
  value: true
model_pth:
  desc: null
  value: results/train-from-scratch-best.pth
_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1713187333.0
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.8.18
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
